<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>RelicLauncher.Bootstrap</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RelicLauncher.App\RelicLauncher.App.csproj" />
  </ItemGroup>
</Project>
