<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>RelicLauncher.Testing</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RelicLauncher.Core\RelicLauncher.Core.csproj" />
  </ItemGroup>
</Project>
