<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>RelicLauncher.Themes.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RelicLauncher.Core\RelicLauncher.Core.csproj" />
    <ProjectReference Include="..\..\src\RelicLauncher.Themes\RelicLauncher.Themes.csproj" />
  </ItemGroup>
</Project>
